services:
  # Ubuntu 22.04 VPS
  ubuntu-vps:
    build: 
      context: ./project/distros/ubuntu
    container_name: ubuntu-vps
    hostname: ubuntu-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2201:22"      # SSH access
      - "8001:80"      # HTTP
      - "8101:8080"    # Alt HTTP
      - "3001:3000"    # Node.js apps
      - "5001:5000"    # Python apps
    volumes:
      - ubuntu-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.10
    profiles:
      - ubuntu
      - debian-family
      - all

  # Debian 12 VPS
  debian-vps:
    build: 
      context: ./project/distros/debian
    container_name: debian-vps
    hostname: debian-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2202:22"      # SSH access
      - "8002:80"      # HTTP
      - "8102:8080"    # Alt HTTP
      - "3002:3000"    # Node.js apps
      - "5002:5000"    # Python apps
    volumes:
      - debian-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.20
    profiles:
      - debian
      - debian-family
      - all

  # Rocky Linux 9 VPS
  rocky-vps:
    build: 
      context: ./project/distros/rocky
    container_name: rocky-vps
    hostname: rocky-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2203:22"      # SSH access
      - "8003:80"      # HTTP
      - "8103:8080"    # Alt HTTP
      - "3003:3000"    # Node.js apps
      - "5003:5000"    # Python apps
    volumes:
      - rocky-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.30
    profiles:
      - rocky
      - redhat-family
      - all

  # CentOS Stream 9 VPS
  centos-vps:
    build: 
      context: ./project/distros/centos
    container_name: centos-vps
    hostname: centos-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2204:22"      # SSH access
      - "8004:80"      # HTTP
      - "8104:8080"    # Alt HTTP
      - "3004:3000"    # Node.js apps
      - "5004:5000"    # Python apps
    volumes:
      - centos-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.40
    profiles:
      - centos
      - redhat-family
      - all

  # Alpine Linux VPS (Lightweight)
  alpine-vps:
    build: 
      context: ./project/distros/alpine
    container_name: alpine-vps
    hostname: alpine-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2205:22"      # SSH access
      - "8005:80"      # HTTP
      - "8105:8080"    # Alt HTTP
      - "3005:3000"    # Node.js apps
      - "5005:5000"    # Python apps
    volumes:
      - alpine-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.50
    profiles:
      - alpine
      - debian-family
      - all

  # openSUSE Leap VPS
  suse-vps:
    build: 
      context: ./project/distros/suse
    container_name: suse-vps
    hostname: suse-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2206:22"      # SSH access
      - "8006:80"      # HTTP
      - "8106:8080"    # Alt HTTP
      - "3006:3000"    # Node.js apps
      - "5006:5000"    # Python apps
    volumes:
      - suse-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.60
    profiles:
      - suse
      - suse-family
      - all

  # Arch Linux VPS
  arch-vps:
    build: 
      context: ./project/distros/arch
    container_name: arch-vps
    hostname: arch-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2207:22"      # SSH access
      - "8007:80"      # HTTP
      - "8107:8080"    # Alt HTTP
      - "3007:3000"    # Node.js apps
      - "5007:5000"    # Python apps
    volumes:
      - arch-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.70
    profiles:
      - arch
      - arch-family
      - all

  # Slackware Linux VPS
  slackware-vps:
    build: 
      context: ./project/distros/slackware
    container_name: slackware-vps
    hostname: slackware-vps
    privileged: true
    restart: unless-stopped
    ports:
      - "2208:22"      # SSH access
      - "8008:80"      # HTTP
      - "8108:8080"    # Alt HTTP
      - "3008:3000"    # Node.js apps
      - "5008:5000"    # Python apps
    volumes:
      - slackware-data:/var/lib/docker
      - ./project/shared:/home/vpsuser/shared
      - ./project/deployments:/home/vpsuser/deployments
    networks:
      vps-network:
        ipv4_address: 172.20.0.80
    profiles:
      - slackware
      - slackware-family
      - all

  # Test web server (for deployment testing)
  test-nginx:
    image: nginx:alpine
    container_name: test-nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - vps-network
    profiles:
      - testing
      - all

volumes:
  ubuntu-data:
  debian-data:
  rocky-data:
  centos-data:
  alpine-data:
  suse-data:
  arch-data:
  slackware-data:

networks:
  vps-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
